<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:activities="platform:/plugin/SDMLanguage/model/SDMLanguage.ecore#//activities" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xmlns:org.moflon.sdm.compiler.democles.validation.controlflow="platform:/plugin/org.moflon.sdm.compiler.democles.validation.controlflow/model/Controlflow.ecore" name="learningboxlanguage" nsURI="platform:/plugin/org.moflon.handbook.learningboxlanguage/model/Learningboxlanguage.ecore" nsPrefix="org.moflon.handbook.learningboxlanguage">
  <eClassifiers xsi:type="ecore:EClass" name="Box">
    <eOperations xsi:type="activities:MoflonEOperation" name="determineNextSize">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="toString">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="initializeBox">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eOperations>
    <eOperations xsi:type="org.moflon.sdm.compiler.democles.validation.controlflow:MoflonOperation" name="addToStringRep"/>
    <eOperations xsi:type="org.moflon.sdm.compiler.democles.validation.controlflow:MoflonOperation" name="grow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedPartition" upperBound="-1" eType="//Partition" containment="true" eOpposite="//Partition/box"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stringRep" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partition">
    <eOperations xsi:type="activities:MoflonEOperation" name="check">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eParameters name="card" eType="//Card"/>
      <eParameters name="guess">
        <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eParameters>
    </eOperations>
    <eOperations xsi:type="activities:MoflonEOperation" name="removeCard" eType="//Card">
      <eParameters name="card" eType="//Card"/>
    </eOperations>
    <eOperations xsi:type="org.moflon.sdm.compiler.democles.validation.controlflow:MoflonOperation" name="empty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="card" upperBound="-1" eType="//Card" containment="true" eOpposite="//Card/cardContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="box" eType="//Box" eOpposite="//Box/containedPartition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="//Partition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="//Partition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="index" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partitionSize" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Card">
    <eOperations xsi:type="org.moflon.sdm.compiler.democles.validation.controlflow:MoflonOperation" name="invert"/>
    <eOperations xsi:type="org.moflon.sdm.compiler.democles.validation.controlflow:MoflonOperation" name="printCard"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cardContainer" eType="//Partition" eOpposite="//Partition/card"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="back" ordered="false">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="face" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partitionHistory" ordered="false" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FastCard" eSuperTypes="//Card"/>
</ecore:EPackage>
